{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-list.backend.fullname" . }}
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort.enabled }}
      nodePort: {{ .Values.backend.service.nodePort.port }}
      {{- end }}
  selector:
    {{- include "todo-list.backend.selectorLabels" . | nindent 4 }}
{{- end }}
