{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-list.database.fullname" . }}
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
  selector:
    {{- include "todo-list.database.selectorLabels" . | nindent 4 }}
{{- end }}
