apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-list.secret.name" . }}
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.auth.rootPassword | quote }}
